# SQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:55432/postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:55432/postgres
quarkus.datasource.reactive.max-size=20
# DATABASE STRATEGY
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.packages=org.app
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
quarkus.hibernate-orm.mapping.preferred-enum-type=STRING
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.log.highlight-sql=true
quarkus.hibernate-orm.log.jdbc-warnings=true
quarkus.hibernate-orm.log.queries-slower-than-ms=1000
# devservices
quarkus.datasource.devservices.enabled=false
